language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "joyxu"
  - git config user.email "xuwei04@gmail.com"
  - git add .
  - git commit -m "Update - auto deploy by Travis CI."
  - git push --force --quiet "https://${GIT_AUTH_TOKEN}@${GITHUB_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
  global:
    # bugfix: use https, not git.
    # https://github.com/hhstore/hhstore.github.io.git
    - GITHUB_REF: github.com/joyxu/joyxu.github.com.git
