language: node_js
node_js:
- 10
install:
- npm install -g hexo-cli
script:
- git submodule init      # 用于更新主题,更新源为自己的主题项目，否则会clone最新NexT主题，而官方主题配置文件没有设置
- git submodule update
- cp next_config.yml ./themes/next/_config.yml
- hexo clean && hexo g

after_script:
- cd ./public
- git init
- git config user.name "joyxu"
- git config user.email "xuwei04@gmail.com"
- ls -l
- git add -A
- git commit -m "Update - auto deploy by Travis CI."
- git push --force --quiet "https://${GIT_AUTH_TOKEN}@${GITHUB_REF}" master:master
branches:
  only:
  - blog_source
env:
  global:
  - GITHUB_REF: github.com/joyxu/joyxu.github.com.git
  - secure: "nsJ6m57NdehlU5OtyOCDwH8JcQW0+3TI6YrOylS9F2n5O9EM3crEWkJAJWPsSDuBtowULPzta+MvDtFY603dwG0ZQp8hsM8GeE9sd/iCSN/aQucuE+xyqI13EEd0xErySGjUEWWDRxUXljpQkeRJTLCdefLqZEvOcgjSpfTYOs400RCenS4ln5hQnFxIRYC915hbdJkEc6zZxl6ukwhBs3VKRePeyotWVt0qrhsKz29KTcCTDw8jsnkLnGgeMbaBN8es85vVacw5PP+XmMHP/Pjehepif+wY629spAUPgukSOb5RLhWRcHViYfghoC6b/rAxAp144ZTBBsvRCvNJbUrXn18VRXt5QNPhOjjdVT03sK4ZWddiwT/lHXDehOUTVpV2c/U61zp/TDn4OU40yWUOcIB11xec/e3hEbElCP/wQ2+ph1j53fDrGTO54Kn1LZHr6wsEhudweOa5L6TDB7kpQvbCWOLEWphqsFKpfPev4mA4ygv5J94jDbvzeO6kJHeSSjjUTO+JDpzpq+A6SJpI7ZNYkm3lvUXdpox21urxLAn01EgrBe7/kYsWIWXXWCOEe/80xdozjL9XdGebfdgM+oI5WKaHnxC9G7yE4tx9OpPZ6kPvvkvB9l6T7fQD45p25H1V1yCdOJK9yrO7TIRWJH+NvgGUvVVY+tTD0Ro="

