language: node_js
node_js: stable
install:
- npm install
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "joyxu"
- git config user.email "xuwei04@gmail.com"
- git add .
- git commit -m "Update - auto deploy by Travis CI."
- git push --force --quiet "https://${GIT_AUTH_TOKEN}@${GITHUB_REF}" master:master
branches:
  only:
  - blog_source
env:
  global:
  - GITHUB_REF: github.com/joyxu/joyxu.github.com.git
dd:
  secure: lxbMFpioRmlIJw/SBWhq4zEKIS72lj6fA6Dm+cn7HSnhvQrgHM/Bf3QB9P+GUAmDhpqY/lXs1yKxowFK7qJ25a9IIdv10051zMLBpuPcpsokBOcK55Nw3w1+wM0e5REQrDD61yrgDi0V8r/o8MKLnsXtrxqW6xVDXvsn9kEAHdcpDM7gRR+rea5EXezaunnFvkr4e5dxT6Q81wTbZtxSl94eb2/1BQAR9e96NyvQbxOP8efwr2mvLhxfnoYgaKt4cvPV/PZ4ZG/5W/3iH+qLxOOnxdamFHOMmJu0G6PR1GdCOvIY3iCqZMzha/1broyl4JpZ/Dm+elkBGVBhVSlAzmcdWuL5HS5KkUHBcmIuhCw9meOW/aHgDhbGqhvZsujJeiT7q5xGiHZmIal1G+GPBMsAqoM9neVqIugmDJTbpcj0cuchTLe3+q1zk/SmCNd2xXDwHJWsczO3GUfaT2bf/O495gUyaPR7+VZ7xMUoyQT3TnskGp/s6lnwzSIeg20lTot5O9TVzZFPw6cCe5cSVOe8Vxp9aaVphIYgE2u2GCXUbo46RpkdyP2/IggpZPaF5BA6WXoX+7p4hQIg6Agv8PqxDQZYjY1ePRVbq4rcDFmpC6OHkz7/jLEGIg7dp1wtroZQv/uddTeF635ZsyAWmg6SKCfqUhKTXW1fKBzKFok=
