# Action 的名字
name: Hexo Auto Deploy

on:
  # 触发条件1：main 分支收到 push 后执行任务。
  push:
    branches:
      - blog_source
  # 触发条件2：手动按钮
  workflow_dispatch:

# 这里放环境变量,需要替换成你自己的
env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: joyxu
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: weixu_2008@163.com
  # Hexo 编译后要部署的 github 仓库
  GIT_DEPLOY_REPO: joyxu/joyxu.github.com
  # Hexo 编译后要部署到的分支
  GIT_DEPLOY_BRANCH: master
 
jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [10]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: blog_source

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          # coding 已取消同步
          ssh-keyscan -t rsa e.coding.net >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa gitee.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install
          # 根据你安装的组件进行安装
          #npm uninstall hexo-generator-index --save
          #npm install hexo-baidu-url-submit hexo-generator-index2 hexo-symbols-count-time hexo-blog-encrypt hexo-deployer-git --save
          #cp next_config.yml ./themes/next/_config.yml

      - name: Deploy hexo
        run: |
          #git submodule init
          #git submodule update
          cp next_config.yml ./themes/next/_config.yml
          hexo clean && hexo g
          cd ./public
          git init
          tree -lh
          git add -A
          git commit -m "Update - auto deploy by Travis CI."
          git push --force --quiet "https://${{secrets.HEXO_TOKEN}}@github.com/${GIT_DEPLOY_REPO}" master:master
